version: 2.1
orbs:
  slack: circleci/slack@3.2.0

executors:
  jdk-8:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

jobs:
  build:
    executor: jdk-8
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - run: mvn dependency:go-offline

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn clean install

      # Save built artifacts
      - run: |
          set -xu
          mkdir -p artifacts
          cp -r target/*.jar artifacts/

      - store_artifacts:
          path: artifacts
          destination: jars

      - persist_to_workspace:
          root: .
          paths:
            - target
      - slack/status:
          fail_only: true
          success_message: New version built
          failure_message: Error on main branches build.
          webhook: https://hooks.slack.com/services/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

  deploy:
    executor: jdk-8
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - attach_workspace:
          at: .

      - run: echo -e $GPG_KEY | gpg --import --no-tty --batch --yes

      - run: mvn deploy -s .circleci/settings.xml -DskipTest=true

      - slack/status:
          only_for_branches: develop,master
          success_message: New version deployed
          failure_message: Error deploying new version
          webhook: https://hooks.slack.com/services/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

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
