version: 2.1
orbs:
  slack: cimg/slack@3.2.0

executors:
  jdk-8:
    docker:
      - image: cimg/openjdk:8-jdk
    working_directory: ~/repo

jobs:
  branches:
    executor: jdk-8
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn clean package -P branches,unit-tests

      - slack/status:
          fail_only: true
          success_message: Branch passes compile + unit-tests
          failure_message: Branch failed compile + unit-tests
          webhook: https://hooks.slack.com/services/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

  develop:
    executor: jdk-8
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn clean package -P unit-tests,sources

      - slack/status:
          fail_only: true
          success_message: New development version built
          failure_message: Error on develop branch build
          webhook: https://hooks.slack.com/services/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

  rc:
    executor: jdk-8
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn clean package -P unit-tests,integration-tests,sources

      - slack/status:
          fail_only: true
          success_message: Release candidate built
          failure_message: Error on release candidate build
          webhook: https://hooks.slack.com/services/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

  tag:
    executor: jdk-8
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn clean package -P sources,javadoc

      - slack/status:
          fail_only: true
          success_message: New development version built
          failure_message: Error on develop branch build
          webhook: https://hooks.slack.com/services/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

  deploy:
    executor: jdk-8
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - attach_workspace:
          at: .

      - run: echo -e $GPG_KEY | gpg --import --no-tty --batch --yes

      - run: mvn deploy -s .circleci/settings.xml -P sources,javadoc -DskipTest=true

      - slack/status:
          only_for_branches: develop,master
          success_message: New version deployed
          failure_message: Error deploying new version
          webhook: https://hooks.slack.com/services/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

workflows:
  version: 2
  branches:
    jobs:
      - branches:
          filters:
            branches:
              ignore:
                - /rc-.*/
                - develop
                - master
  release-candidate:
    jobs:
      - rc:
          filters:
            branches:
              only:
                - /rc-.*/
      - deploy:
          requires:
            - rc
  develop:
    jobs:
      - develop:
          filters:
            branches:
              only:
                - develop
      - deploy:
          requires:
            - develop

  release:
    jobs:
      - tag:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - tag
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
